cache:
  build: cache
  links:
    - wordpress:bloglb
  ports:
    - 80

wordpress:
  build: .
  links:
    - db:mysql
  ports:
    - 80

db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: example
